// import type { Metadata } from "next";
// import { Poppins, Allura } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/footer";
// import { CartProvider } from "./Context/cartcontext";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300","400","500","600","700"],
//   variable: "--font-poppins",
// });

// const allura = Allura({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-allura",
// });

// export const metadata: Metadata = {
//   title: "LuxeTick Watch Ecom Website",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} ${allura.variable}`}>
//         <CartProvider>
//         <Navbar />
//         {children}
//         <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import ClientWrapper from "./components/clientwrapper";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import { CartProvider } from "./Context/cartcontext";
import { Poppins, Allura } from "next/font/google";

export const metadata: Metadata = {
  title: "LuxeTick Watch Ecom Website",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  variable: "--font-poppins",
});

const allura = Allura({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-allura",
});


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${allura.variable}`}>
        <ClientWrapper>
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
          </CartProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}