// import type { Metadata } from "next";
// import ClientWrapper from "./components/clientwrapper";
// import Navbar from "./components/Navbar";
// import Footer from "./components/footer";
// import { CartProvider } from "./context/cartcontext";
// import { Poppins, Allura } from "next/font/google";
// import { WishlistProvider } from "./context/wishlistcontext";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "LuxeTick Watch Ecom Website",
//   description: "Generated by create next app",
// };

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["300","400","500","600","700"],
//   variable: "--font-poppins",
// });

// const allura = Allura({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-allura",
// });


// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} ${allura.variable}`}>
//         <ClientWrapper>
//           <CartProvider>
//             <WishlistProvider>
//             <Navbar />
//             {children}
//             <Footer />
//             </WishlistProvider>
//           </CartProvider>
//         </ClientWrapper>
//       </body>
//     </html>
//   );
// }










// app/layout.tsx
import type { Metadata } from "next";
import ClientWrapper from "./components/clientwrapper";
import Navbar from "./components/Navbar";
import Footer from "./components/footer";
import { CartProvider } from "./context/cartcontext";
import { WishlistProvider } from "./context/wishlistcontext";
import "./globals.css";

export const metadata: Metadata = {
  title: "LuxeTick Watch Ecom Website",
  description: "Generated by create next app",
};

// RootLayout
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientWrapper>
          <CartProvider>
            <WishlistProvider>
              <Navbar />
              {children}
              <Footer />
            </WishlistProvider>
          </CartProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}